name: "\U0001F680 Feature Request"
description: How to create an issue for requesting a feature
title: "[Feature Request] request title"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
        Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.
  - type: textarea
    id: description
    attributes:
      label: 🚀 Feature
      description: A clear and concise description of the feature proposal.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Please outline the motivation for the proposal. Is your feature request related to a problem? e.g.,"I'm always frustrated when [...]". If this is related to another GitHub issue, please link here too.
  - type: textarea
    id: pitch
    attributes:
      label: Pitch
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered, if any.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
          required: true
