name: root
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0=0
  - pip=22.3.1
  - python=3.7
  - pytorch=1.11.0=py3.7_cpu_0
  - pip:
    - gymnasium
    - cloudpickle
    - opencv-python-headless
    - pandas
    - numpy
    - matplotlib
    - sphinx_autodoc_typehints
    - sphinx>=4.2
    - sphinx_rtd_theme>=1.0
    - sphinx_copybutton
