name: root
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0=0
  - pip=24.2
  - python=3.11
  - pytorch=2.5.0=py3.11_cpu_0
  - pip:
    - gymnasium
    - cloudpickle
    - opencv-python-headless
    - pandas
    - numpy
    - matplotlib
    - sphinx>=5,<8
    - sphinx_rtd_theme>=1.3.0
    - sphinx_copybutton
