name: root
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0=0
  - pip=21.1
  - python=3.10
  - pytorch=2.0.0=py3.10_cpu_0
  - pip:
    - gym==0.21
    - cloudpickle
    - opencv-python-headless
    - pandas
    - numpy
    - matplotlib
    - sphinx_autodoc_typehints
    - sphinx>=4.2
    - sphinx_rtd_theme>=1.0
    - sphinx_copybutton
