name: root
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0=0
  - pip=20.2
  - python=3.6
  - pytorch=1.8.1=py3.6_cpu_0
  - pip:
    - gym>=0.17.2
    - cloudpickle
    - opencv-python-headless
    - pandas
    - numpy
    - matplotlib
    - sphinx_autodoc_typehints
    - sphinx>=4.2
    # See https://github.com/readthedocs/sphinx_rtd_theme/issues/1115
    - sphinx_rtd_theme>=1.0
